- platform: template
  sensors:
      amazon_dot_lr:
        friendly_name: 'Amazon Dot LR'
        value_template: "{{ 'Online' if is_state('device_tracker.dot_livingroom', 'home') else 'Offline' }}"

      amazon_dot_kn:
        friendly_name: 'Amazon Dot KN'
        value_template: "{{ 'Online' if is_state('device_tracker.dot_kitchen', 'home') else 'Offline' }}"

      tycho:
        friendly_name: 'tycho'
        value_template: "{{ 'Online' if is_state('device_tracker.jarvis', 'home') else 'Offline' }}"

      tightbeam:
        friendly_name: 'tightbeam'
        value_template: "{{ 'Online' if is_state('device_tracker.tightbeam', 'home') else 'Offline' }}"

      appletv:
        friendly_name: 'Apple Tv'
        value_template: "{{ 'On' if is_state('media_player.apple_tv', 'on') else 'Off' }}"

      xboxone:
        friendly_name: 'xboxone'
        value_template: "{{ 'Online' if is_state('device_tracker.xboxone', 'home') else 'Offline' }}"

      chromecast_livingroom:
        friendly_name: 'Chromecast - Living Room'
        value_template: "{{ 'On' if is_state('media_player.chromecast_livingroom', 'on') else 'Off' }}"

      smartthings:
        friendly_name: 'SmartThings'
        value_template: "{{ 'Online' if is_state('device_tracker.d052a8170fef', 'home') else 'Offline' }}"

      samsungtv:
        friendly_name: 'Samsung Tv'
        value_template: "{{ 'On' if is_state('media_player.pn60e550_pn60e550', 'on') else 'Off' }}"

      honeywell:
        friendly_name: 'Honeywell'
        value_template: "{{ 'Online' if is_state('device_tracker.gateway2f3bca', 'home') else 'Offline' }}"

      kat_mini:
        friendly_name: "Kat's Mini"
        value_template: "{{ 'Online' if is_state('device_tracker.katherinesmini', 'home') else 'Offline' }}"

      jeff_mbp:
        friendly_name: "Jeff's MBP"
        value_template: "{{ 'Online' if is_state('device_tracker.jeffreysmbp', 'home') else 'Offline' }}"

      jeff_work_mbp:
        friendly_name: "Jeff's Work MBP"
        value_template: "{{ 'Online' if is_state('device_tracker.jstonemac', 'home') else 'Offline' }}"

      jeff_ipad:
        friendly_name: "Jeff's iPad"
        value_template: "{{ 'Online' if is_state('device_tracker.jeffreystonesipad', 'home') else 'Offline' }}"

      kat_ipad:
        friendly_name: "Kat's iPad"
        value_template: "{{ 'Online' if is_state('device_tracker.katherinesipad', 'home') else 'Offline' }}"

      eero_livingroom:
        friendly_name: "Eero Living Room"
        value_template: "{{ 'Online' if is_state('device_tracker.eero_livingroom', 'home') else 'Offline' }}"

      eero_loft:
        friendly_name: "Eero Loft"
        value_template: "{{ 'Online' if is_state('device_tracker.eero_loft', 'home') else 'Offline' }}"

      smoke_kitchen:
        friendly_name: "Kitchen Smoke"
        value_template: "{{ 'Smoke Detected!' if is_state('device_tracker.eero_loft', 'smoke') else 'All Clear' }}"

      security_status:
        friendly_name: 'Security System'
        value_template: '{{ "Armed" if is_state("input_boolean.secure_mode", "on") else "Disarmed" }}'
        icon_template: '{%- if is_state("input_boolean.secure_mode", "on") %}mdi:lock{% else %}mdi:lock-open{%- endif %}'

      garage_motion:
        friendly_name: "Garage Motion"
        value_template: "{{ 'open' if is_state('sensor.garage_dome_sensor', 'motion') else 'clear' }}"

      washer_status:
        friendly_name: "Washer Status"
        value_template: >-
          {% if states('sensor.washer_power') | float > 0 %}
            running
          {% else %}
            idle
          {%endif %}
        


      
