
#
#
# Presence Automations
#
#
#####################

- alias: Family Has arrived
  trigger:
  - entity_id: sensor.family_status
    from: away
    platform: state
    to: home
  action:
  - service: script.standby
  - service: script.driveway_on
  - service: script.vacation_canceled
  - service: script.washer_finished_notification
  - service: script.appliances_on

- alias: Family Has Left
  trigger:
  - entity_id: sensor.family_status
    from: home
    platform: state
    to: away
  condition:
  - condition: state
    entity_id: input_boolean.guest_mode
    state: 'off'
  action:
  - service: script.close_garage
  - service: script.lockdown
  - service: script.appliances_off

- alias: Family Devices Have arrived
  trigger:
  - entity_id: group.family
    from: not_home
    platform: state
    to: home
  condition:
  - condition: state
    entity_id: sensor.family_presence
    state: 'away'
  action:
  - service: script.family_is_home

#- alias: Family Devices Have Left
#  trigger:
#  - entity_id: group.family
#    from: home
#    platform: state
#    to: not_home
#  condition:
#  - condition: state
#    entity_id: sensor.family_status
#    state: 'home'
#  action:
#  - service: script.family_is_away

- alias: Jeff Arrives Home
  trigger:
  # - entity_id: device_tracker.owntracks_jeffreystonesiphone
  #   event: enter
  #   platform: zone
  #   zone: zone.home
  - entity_id: sensor.jeff_presence
    from: 'not present'
    platform: state
    to: 'present'
  action:
  - service: script.jeff_destination_arrived
  - service: script.driveway_on
  - service: input_boolean.turn_off
    entity_id: input_boolean.jeff_heading_home
 
- alias: Jeff Arrives At Summit
  trigger:
  - entity_id: device_tracker.owntracks_jeffreystonesiphone
    event: enter
    platform: zone
    zone: zone.summit
  action:
  - service: script.jeff_destination_arrived
  - service: script.jeff_at_work_notification

- alias: Kat Arrives Home Notification
  trigger:
  - entity_id: device_tracker.katherinestonesiphone
    event: enter
    platform: zone
    zone: zone.home
  action:
  - service: script.kat_is_home_audible
  - service: input_boolean.turn_off
    entity_id: input_boolean.kat_heading_home
  - service: script.driveway_on

- alias: Kat Arrives Zoo Notification
  trigger:
  - platform: zone
    event: enter
    zone: zone.zoo_atlanta
    entity_id: device_tracker.katherinestonesiphone
  condition:
  - condition: state
    entity_id: input_boolean.text_notify_jeff
    state: 'on'
  action:
  - service: notify.ios_jeffreystonesiphone
    data:
      message: Kat is at Zoo Atlanta

- alias: Kat Leaves Zoo Notification
  trigger:
  - platform: zone
    event: leave
    zone: zone.zoo_atlanta
    entity_id: device_tracker.katherinestonesiphone
  condition:
  - condition: state
    entity_id: input_boolean.text_notify_jeff
    state: 'on'
  action:
  #- service: notify.ios_jeffreystonesiphone
  #  data:
  #    message: Kat left Zoo Atlanta
  - service: input_boolean.turn_on
    entity_id: input_boolean.kat_heading_home
