#
#
# Switches
#
############

- alias: "Kitchen - Turn Off Lights"
  trigger:
    - platform: state
      entity_id: light.kitchen_cabinets
      to: 'off'
  action:
    - service: light.turn_off
      data:
        entity_id: light.kitchen_light_strip

- alias: "Kitchen - Turn On Lights"
  trigger:
    - platform: state
      entity_id: light.kitchen_cabinets
      to: 'on'
  action:
    - service: light.turn_on
      data:
        entity_id: light.kitchen_light_strip